### ISSUE TITLE
Highlight color makes suggestions unreadable

### ISSUE THREAD

**Issue by everdrone** [smockle/xcode-default-theme#1]
<img width="332" alt="screenshot 2018-10-28 at 08 16 43" src="https://user-images.githubusercontent.com/22671061/47613172-17890d80-da8a-11e8-8740-abf9a35910fa.png">
<img width="652" alt="screenshot 2018-10-28 at 08 16 55" src="https://user-images.githubusercontent.com/22671061/47613173-1b1c9480-da8a-11e8-9631-fc1a27eaeb46.png">

**Comment by smockle** [comment]
Thanks for reporting this! I’ve merged a fix (#2) and this should ship with the next version of the theme extension.

**Comment by everdrone** [comment]
Awesome! Can’t wait to try it out!
