### ISSUE TITLE
Light theme: white terminal text color should be readable

### ISSUE THREAD

**Issue by madig** [smockle/xcode-default-theme#5]
Currently:

![image](https://user-images.githubusercontent.com/380829/59600752-fe58ce00-90f9-11e9-900c-95c667e8340e.png)

Default light theme:

![image](https://user-images.githubusercontent.com/380829/59600771-0fa1da80-90fa-11e9-9e05-b1afd1686b70.png)

**Comment by madig** [comment]
(Removing the theme's own definition of the `terminal.*white` colors seems to be enough)

**Comment by smockle** [comment]
> (Removing the theme's own definition of the `terminal.*white` colors seems to be enough)

Thank you for reporting this and providing the solution!

I’ve removed `terminal.*white` via https://github.com/smockle/xcode-default-theme/commit/c9dd9d0c5ac794b6f296438d36e1d966e114e1cd and https://github.com/smockle/xcode-default-theme/commit/fff90ee5c804b7019627cd66391cca656cde0955.

**Comment by smockle** [comment]
These changes have been published in version 2.0.16.
